# Generated by Django 3.0.5 on 2020-05-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MathuraMed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicines',
            name='category',
            field=models.CharField(default='', max_length=40),
        ),
    ]
